- conf/config.yaml
- datasets/base_dataset.py
- datasets/modelnet_dataset.py
- datasets/s3dis_dataset.py
- datasets/shapenet_dataset.py
- datasets/transforms.py
- models/KPConv/modules.py
- models/KPConv/nn.py
- models/RSConv/nn.py
- models/RandLANet/nn.py
- models/base_model.py
- models/core_modules.py
- models/core_sampling_and_search.py
- models/pointnet2/modules.py
- models/pointnet2/nn.py
- models/unet_base.py
- models/utils.py
- test/test_dataset.py
- test/test_models.py
- train.py
What's new:
- Simpler model building logic
- Model takes a whole dataset as input
- Moved methods from dataset specific implementations to the BaseDataset class
- Pointnet and KPConv can take features as an input as well as just points
> Dynamicinput

- conf/models/segmentation.yaml
- models/pointnet2/modules.py
pointnet2 was broken with resolver by commit: https://github.com/nicolas-chaulet/deeppointcloud-benchmarks/commit/c26e759adf36d649c4fd973c17264d8494f8dfbb. 
This PR fixes it so the test_models test case passes.
> Fix resolver with pointnet2

- models/core_sampling_and_search.py
- test/test_sampler.py
Working towards multiscale pointnet++
> Adding support for multiscale radius search

- conf/models/segmentation.yaml
- datasets/shapenet_dataset.py
- models/core_modules.py
- models/core_sampling_and_search.py
- models/pointnet2/modules.py
- models/pointnet2/nn.py
- models/unet_base.py
- test/test_models.py
- test/test_sampler.py
Support for multi scale pointnet.
Also introduces a new base conv for multi scale convolutions.
> Multiscale pointnet

- conf/config.yaml
- datasets/base_dataset.py
- datasets/batch.py
- datasets/s3dis_dataset.py
- models/pointnet2_customkernel/nn.py
- poetry.lock
- test/test_batch.py
Please ignore PN2 for now. But dataloader is ready to go
> Adding classic batch dataloader

- conf/config.yaml
- conf/models/segmentation.yaml
- datasets/s3dis_dataset.py
- models/core_modules.py
- models/pointnet2_customkernel/modules.py
- models/pointnet2_customkernel/nn.py
- train.py
Customizable PN2, stills remains to add the following for a fully flexible architecture:
- Support  single scale
- Inner most layer
> PN2 flexible

- README.md
- benchmark/shapenet/pointnet2_original.md
- conf/config.yaml
- conf/hydra/job_logging/custom.yaml
- conf/models/segmentation.yaml
- datasets/base_dataset.py
- datasets/s3dis_dataset.py
- datasets/shapenet_dataset.py
- datasets/transforms.py
- find_env.py
- metrics/base_tracker.py
- metrics/model_checkpoint.py
- models/KPConv/kernel_utils.py
- models/KPConv/plyutils.py
- models/PointNet/nn.py
- models/base_model.py
- models/core_modules.py
- models/dense_modules.py
- models/pointnet2_dense/nn.py
- models/unet_base.py
- schedulers/lr_schedulers.py
- test/mockdatasets.py
- train.py
- utils_folder/utils.py
This PR includes various improvements:
- possibility for having learning rate schedulers
- possibility for adding category information to the segmentation task
- logs to file as well as to stdout
> Tuning pn2 and training

- conf/config.yaml
- conf/models/segmentation.yaml
- models/dense_modules.py
- models/partial_dense_modules.py
Follows this
https://github.com/charlesq34/pointnet2/blob/master/part_seg/train_one_hot.py
> PN2 original architecture for part-seg

- poetry.lock
- pyproject.toml
Pin the version of torch-points using tags in torch-points repo
> Proper torch-points release

- conf/config.yaml
- metrics/model_checkpoint.py
- models/base_model.py
- models/model_building_utils/model_definition_resolver.py
- schedulers/lr_schedulers.py
- train.py
- utils_folder/utils.py
This PR changes the behaviour of the checkpoints (hopefully for the better).
Now, models are saved in the hydra directory and models can be loaded from the checkpoint_dir path. Also supports saving and loading the learning rate config.
> Simpler checkpoint management

- src/datasets/base_dataset.py
- src/datasets/classification/modelnet_dataset.py
- src/datasets/segmentation/s3dis1x1_dataset.py
- src/datasets/segmentation/s3dis_dataset.py
- src/datasets/segmentation/shapenet_dataset.py
Adds support in the base_dataset for validation sets
> Support for a validation dataset

- README.md
- poetry.lock
- pyproject.toml
@tchaton a quick one that updates pytorch in preparation for the Minkowski nets. Also added some help to explain how to update
> Updating pytorch to 1.3

- docs/index.md
I've looked over `index.md` and made some changes. I'm submitting this PR now to check that you guys are happy to make big-ish changes like I've made here, or if you want me just to focus on grammar errors and typos. If you're happy with what I've done here I'll review `how_to_do.md` as well.
> Review Index Doc

- conf/data/segmentation/shapenet-fixed.yaml
- conf/data/segmentation/shapenet.yaml
- conf/models/segmentation/kpconv.yaml
- conf/training/kpconv.yaml
- src/core/data_transform/__init__.py
- src/core/data_transform/transforms.py
- src/datasets/base_dataset.py
- src/datasets/segmentation/s3dis.py
- src/datasets/segmentation/shapenet.py
- src/models/segmentation/base.py
- src/models/segmentation/kpconv.py
- src/models/segmentation/pointnet.py
- src/models/segmentation/pointnet2.py
- src/models/segmentation/rsconv.py
- src/utils/__init__.py
- src/utils/config.py
This PR fixes a major bug in the evaluation of the loss on the test set. It also moves the logic for creating transforms out of the code and in the config file for shapenet
> Loss computation and transforms

- conf/training/default.yaml
- conf/training/kpconv.yaml
- src/core/schedulers/lr_schedulers.py
- src/metrics/shapenet_part_tracker.py
- train.py
Nothing major just a few minor fixes
> Patches here and there

- conf/data/segmentation/shapenet.yaml
- conf/models/segmentation/kpconv.yaml
- conf/training/kpconv.yaml
- src/core/common_modules/base_modules.py
- src/models/segmentation/kpconv.py
- src/modules/KPConv/blocks.py
- src/modules/KPConv/partial_dense.py
- train.py
Contains a few aditions to Wandb logging as well as a mutlihead classifier!
> Multi head segmentation

- conf/data/segmentation/s3disfused-fixed.yaml
- conf/data/segmentation/s3disfused.yaml
- conf/models/segmentation/kpconv.yaml
- conf/models/segmentation/rsconv.yaml
- conf/training/kpconv.yaml
- conf/visualization/default.yaml
- dashboard/dashboard.ipynb
Some config updates for s3dis support
> Configs for s3dis training

- poetry.lock
- pyproject.toml
- src/core/losses/dirichlet_loss.py
- src/core/spatial_ops/neighbour_finder.py
- src/datasets/registration/utils.py
- test/test_transform.py
This PR updates torch_points with a full CPU implementation of all kernels. Ball query now return the distances as well in all cases (CPU and GPU)
> Updating torch points

- conf/data/segmentation/shapenet_sparse.yaml
- src/core/data_transform/sparse_transforms.py
- src/models/segmentation/minkowski.py
A few minor glitches in Minkowski code base.
> Typos here and there

- docs/conf.py
- poetry.lock
- pyproject.toml
- requirements.txt
- src/core/base_conv/dense.py
- src/core/base_conv/message_passing.py
- src/core/base_conv/partial_dense.py
- src/core/losses/dirichlet_loss.py
- src/core/spatial_ops/neighbour_finder.py
- src/core/spatial_ops/sampling.py
- src/datasets/registration/utils.py
- src/modules/RSConv/dense.py
- src/modules/pointnet2/dense.py
This is the first step for renaming the repo
> Using Pypi version of torch-points

- conf/config.yaml
- conf/data/segmentation/s3disfused.yaml
- conf/lr_scheduler/exponential.yaml
- conf/lr_scheduler/multi_step.yaml
- conf/models/segmentation/kpconv.yaml
- conf/training/kpconv.yaml
- src/core/common_modules/base_modules.py
- src/core/data_transform/feature_augment.py
- src/core/data_transform/features.py
- src/datasets/segmentation/s3dis.py
- src/models/base_model.py
- src/models/segmentation/kpconv.py
- src/modules/KPConv/blocks.py
- src/modules/KPConv/convolution_ops.py
Fine tuning of KPConv that match Hugues' setup quite closely
> Kpconv returned

- src/metrics/model_checkpoint.py
- src/utils/config.py
- test/test_model_checkpoint.py
Checkpoint best model was being oeverriden with latest, all the time.
> Fix checkpoint bug

- README.md
- docs/conf.py
- docs/index.rst
- docs/src/advanced.rst
- docs/src/api/filters.rst
- docs/src/api/transforms.rst
- docs/src/gettingstarted.rst
- docs/src/tutorials.rst
- pyproject.toml
Just misses the logo (in principle)
> Changing all references

- test/test_transform.py
- torch_points3d/core/data_transform/features.py
This new XYZFeature add to an x, y, z attribute within data, not to x directly anymore
@humanpose1 update your code accordingly :)
> repare XYZFeatures

- test/test_model_checkpoint.py
- torch_points3d/metrics/base_tracker.py
- torch_points3d/metrics/model_checkpoint.py
- torch_points3d/metrics/registration_tracker.py
- torch_points3d/metrics/segmentation_tracker.py
- torch_points3d/metrics/shapenet_part_tracker.py
- train.py
I've modified a bit the `model_checkpoint.py` so that it's more handy. When we will build a new tracker we need to define the method `get_metric`. We will also need to define the `metric_func` method.
Tell me what you think ;-)
> Metric_func for each tracker

- docs/src/tutorials.rst
- poetry.lock
- pyproject.toml
- requirements.txt
- test/test_api.py
- test/test_bn_scheduler.py
- torch_points3d/applications/kpconv.py
- torch_points3d/applications/pointnet2.py
- torch_points3d/applications/rsconv.py
- torch_points3d/core/base_conv/dense.py
- torch_points3d/core/common_modules/base_modules.py
- torch_points3d/core/common_modules/dense_modules.py
- torch_points3d/core/spatial_ops/neighbour_finder.py
- torch_points3d/metrics/s3dis_tracker.py
- torch_points3d/metrics/segmentation_tracker.py
- torch_points3d/metrics/shapenet_part_tracker.py
- torch_points3d/models/registration/base.py
- torch_points3d/models/registration/pointnet.py
- torch_points3d/models/segmentation/pointnet2.py
- torch_points3d/models/segmentation/rsconv.py
- torch_points3d/modules/RSConv/dense.py
- torch_points3d/modules/pointnet2/dense.py
Some more cleanup
- Remove Erik's code for convs and sequential models
- Simplify API by removing the call to the set_input method
> Removing Erik code

- torch_points3d/datasets/base_dataset.py
- torch_points3d/datasets/segmentation/s3dis.py
The numpy random number generator was generating always the same sequences in each epoch... This PR fixes the behaviour
> Data loader always loads the same data

- CHANGELOG.md
- poetry.lock
- requirements.txt
- test/test_basedataset.py
- torch_points3d/datasets/base_dataset.py
> Fix transform being overriden

- conf/data/segmentation/s3disfused-fixed.yaml
- conf/data/segmentation/s3disfused-sparse.yaml
- conf/data/segmentation/s3disfused.yaml
- conf/training/s3dis_benchmark/kpconv.yaml
- conf/training/s3dis_benchmark/minkowski.yaml
- conf/training/s3dis_benchmark/pointnet2.yaml
- conf/training/s3dis_benchmark/rsconv.yaml
- notebooks/s3dis_explorer.ipynb
- torch_points3d/datasets/segmentation/s3dis.py
Training command line:
```
python train.py task=segmentation model_type=pointnet2 model_name=pointnet2_largemsg dataset=s3disfused-fixed training=s3dis_benchmark/pointnet2
python train.py task=segmentation model_type=kpconv model_name=KPConvPaper dataset=s3disfused training=s3dis_benchmark/kpconv
python train.py task=segmentation model_type=rsconv model_name=RSConv_MSN_S3DIS dataset=s3disfused-fixed training=s3dis_benchmark/rsconv
```
> Introduce a validation set for S3DIS

- CHANGELOG.md
- README.md
- find_neighbour_dist.py
- test/test_model_checkpoint.py
- test/test_trainer.py
- torch_points3d/metrics/model_checkpoint.py
- torch_points3d/trainer.py
- torch_points3d/utils/config.py
- torch_points3d/utils/wandb_utils.py
This will copy the checkpoint file to wandb folder at the end of each epoch
> Save checkpoint to wandb

- CHANGELOG.md
- conf/data/registration/fragment3dmatch_sparse.yaml
- conf/data/registration/test3dmatch_sparse.yaml
- test/test_grid_sampling.py
- test/test_to_sparse.py
- torch_points3d/applications/minkowski.py
- torch_points3d/core/data_transform/grid_transform.py
- torch_points3d/models/registration/minkowski.py
- torch_points3d/models/segmentation/minkowski.py
Implements what we discussed. @humanpose1 I believe I have handled the registration bit correctly but please double check!
> Amending behaviour of grid sampling in the case of sparse coordinates

- test/test_transform.py
- torch_points3d/core/data_transform/transforms.py
> correct mistakes

- torch_points3d/datasets/segmentation/scannet.py
> Fix semantic labels

- docs/conf.py
> Fix doc build

- .pre-commit-config.yaml
- conf/eval.yaml
- conf/training/default.yaml
- conf/training/default_reg.yaml
- conf/training/kpconv.yaml
- conf/training/kpconv_reg.yaml
- conf/training/minkowski_scannet.yaml
- conf/training/pointgroup.yaml
- conf/training/s3dis_benchmark/kpconv.yaml
- conf/training/s3dis_benchmark/minkowski.yaml
- conf/training/s3dis_benchmark/pointnet2.yaml
- conf/training/s3dis_benchmark/rsconv.yaml
- conf/training/sparse_fragment_reg.yaml
- conf/training/votenet.yaml
- torch_points3d/trainer.py
- torch_points3d/utils/wandb_utils.py
Provides a way to save configs for grouping in weight and biases. Also saves the git diff manually, it is not uploaded anymore for some reason... Also allows to select cuda device through hydra
> Save configs and git patch

- conf/data/panoptic/scannet-sparse.yaml
- conf/lr_scheduler/poly_lr.yaml
- conf/models/panoptic/pointgroup.yaml
- conf/training/minkowski_scannet.yaml
- conf/training/pointgroup.yaml
- conf/training/s3dis_benchmark/minkowski.yaml
- notebooks/pointgroup_debug.ipynb
- notebooks/scannet_panoptic.ipynb
- test/data/shapenet/shapenet_config.yaml
- test/test_config/lr_scheduler.yaml
- test/test_config/training_config.yaml
- torch_points3d/applications/conf/minkowski/encoder_2.yaml
- torch_points3d/applications/conf/minkowski/unet_2.yaml
- torch_points3d/metrics/panoptic_tracker.py
- torch_points3d/models/base_model.py
- torch_points3d/models/panoptic/pointgroup.py
- torch_points3d/modules/MinkowskiEngine/res16unet.py
Some minor tweaks to point group. Clustering happens on CPU until we have solved the problem with torch points3d ball query for partial dense data on GPU.
> Pointgroup tune

- docker/Dockerfile.train
Here's the base train dockerfile... I've confirmed it to work for `pip install -r` but not `pip install .`, let me know what your ideas are.
> Train Dockerfile

- .gitignore
- docker/Dockerfile.train
- scripts/cv_s3dis.py
- torch_points3d/datasets/segmentation/s3dis.py
- torch_points3d/metrics/s3dis_tracker.py
- torch_points3d/trainer.py
```
python scripts/cv_s3dis.py checkpoint_dir=`pwd` model_name=pointnet2
```
> add cv_s3dis.py

- scripts/cv_s3dis.py
- torch_points3d/applications/pretrained_api.py
- torch_points3d/modules/MinkowskiEngine/res16unet.py
Adding pretrained weights for Minkowski on s3dis
> Adding links to Minkowski weights for s3dis

- conf/data/segmentation/scannet-fixed.yaml
- conf/data/segmentation/scannet.yaml
- conf/training/scannet_benchmark/pointnet2.yaml
- torch_points3d/datasets/segmentation/s3dis.py
Tiny pull request to update configs on scannet
> Finetunescannet

- conf/models/segmentation/kpconv.yaml
- test/test_models.py
- torch_points3d/modules/KPConv/blocks.py
- torch_points3d/modules/KPConv/kernels.py
@sidml this will do the trick. Closing #368
> Customizable number of kernel points

- .github/workflows/docker_push.yaml
- docker/Dockerfile.train
Automatically builds and pushes a docker image ready for training:
https://hub.docker.com/repository/docker/principialabs/torch-points3d
> Dockerpush

- docker/Dockerfile.train
we need to force cuda on build and redirect the system python to python3 for it to build
> update training dockerfile to support cuda minkowski

- torch_points3d/core/base_conv/message_passing.py
- torch_points3d/utils/wandb_utils.py
Adding the option to resume a training in wandb by just passing teh following to the configuration:
```
wandb.id=<wanbdid>
```
> Some small but nice changes

- torch_points3d/metrics/model_checkpoint.py
Solve https://github.com/nicolas-chaulet/torch-points3d/issues/344
> resolve bug

- notebooks/demo_registration_3dm.ipynb
- notebooks/demo_registration_kitti.ipynb
- scripts/test_registration_scripts/demo_kitti.py
Sorry, I let some mistakes in the notebooks for the demo. Now, everything should be fine :)
> correct some mistakes

- .github/workflows/pythonapp.yml
- conf/data/registration/testeth.yaml
- pyproject.toml
- test/test_registration_metrics.py
- test/test_registration_tracker.py
- torch_points3d/datasets/registration/base_siamese_dataset.py
- torch_points3d/datasets/registration/basetest.py
- torch_points3d/datasets/registration/general3dmatch.py
- torch_points3d/datasets/registration/modelnet.py
- torch_points3d/datasets/registration/testeth.py
- torch_points3d/metrics/registration_metrics.py
- torch_points3d/metrics/registration_tracker.py
Hi, I have added new datasets (also, there are slight modifications). 
Also I have added the new metric proposed in https://arxiv.org/pdf/2003.12841.pdf
Code is taken from https://github.com/iralabdisco/point_clouds_registration_benchmark.
I will add the other datasets in an other PR.
> new datasets for registration benchmark

- scripts/test_registration_scripts/demo_kitti.py
- scripts/test_registration_scripts/evaluate.py
- torch_points3d/core/data_transform/features.py
the rotations around the different axis are centered. For example if the params rot_x is 25,  the rotation is then between -25 and +25 degrees (In my datasets, there were problems because rotation wasn't centered).
And there are other mini changes
> Fix random rotate

- torch_points3d/core/data_transform/grid_transform.py
Updated default parameters to match the ones in MinkowskiEngine
> Fix default parameters to elastic distro

- CHANGELOG.md
- docker/install_python.sh
- torch_points3d/core/data_transform/prebatchcollate.py
Fixing typo in python packages
> Fixing typo and update changelog

- CHANGELOG.md
- conf/data/segmentation/scannet-sparse.yaml
- conf/models/segmentation/sparseconv3d.yaml
- test/test_models.py
- torch_points3d/applications/sparseconv3d.py
- torch_points3d/datasets/base_dataset.py
- torch_points3d/datasets/segmentation/scannet.py
- torch_points3d/metrics/scannet_segmentation_tracker.py
- torch_points3d/trainer.py
Small PR to add SOTA sparseconv
> Bigger network in sparseconv

- conf/data/segmentation/scannet-sparse.yaml
- conf/training/scannet_benchmark/minkowski.yaml
- torch_points3d/applications/sparseconv3d.py
- torch_points3d/core/data_transform/transforms.py
Some minor modifications taht make sparse conv perform as it should on Scannet
> Tuning for scannet

- .devcontainer/Dockerfile.cpu
- .devcontainer/Dockerfile.gpu
- .devcontainer/devcontainer.json
- .devcontainer/setup.sh
- .github/workflows/pythonapp.yml
- docker/build.sh
- docker/install_python.sh
- docker/install_system.sh
@albertotono This will help you with your dev container setup. Once this is done you should be able to run jupyter lab by typing:
```
jupyter lab --allow-root --ip=0.0.0.0
```
Also, for gpu, just switch .cpu for .gpu and add the runArgs to the devcontainer.json.
> Modifying Docker dev container for simpler customisation

- torch_points3d/models/segmentation/sparseconv3d.py
Minor fix that is required for the submission
> SparseConv Forward to ignore y when missing

- conf/data/segmentation/scannet-pvcnn.yaml
- conf/models/segmentation/spvcnn.yaml
- conf/training/spvcnn.yaml
- torch_points3d/models/segmentation/spvcnn.py
- torch_points3d/modules/SPVCNN/blocks.py
- torch_points3d/modules/SPVCNN/modules/__init__.py
- torch_points3d/modules/SPVCNN/modules/dynamic_op.py
- torch_points3d/modules/SPVCNN/modules/dynamic_sparseop.py
- torch_points3d/modules/SPVCNN/modules/layers.py
- torch_points3d/modules/SPVCNN/modules/modules.py
- torch_points3d/modules/SPVCNN/modules/networks.py
- torch_points3d/modules/SPVCNN/spvcnn.py
- torch_points3d/modules/SPVCNN/utils.py
WIP implementation of svpcnn, bottlenecks on set_input for an unknown reason. Even when the input sparsetensor is converted in the forward method, the label is bottlenecking for some reason.
> SVPCNN Network

- docs/src/api/transforms.rst
- test/test_transform.py
- torch_points3d/core/data_transform/__init__.py
- torch_points3d/core/data_transform/transforms.py
A new transform to select params randomly on a specific transform. (We can use it for a GridSampling with a random grid size)
Example are on the tests. 
What do you think ?
> random Param Transform

- docker/install_python.sh
- poetry.lock
- requirements.txt
- torch_points3d/metrics/colored_tqdm.py
Updating to latest pytorch and checking that all still works fine
> Updating packages and fixing issues with progress bar

- conf/models/segmentation/pointnet.yaml
- torch_points3d/models/segmentation/pointnet.py
This PR fixes #521: 
- Fixed the config file for PointNet. Major change: use PARTIAL_DENSE type convolution.
- Fixed class definition to instantiate the model during the __init__ function, as opposed to during set_input() as done previously.
> Bug fixes for PointNet segmentation model

- test/test_registration_tracker.py
- test/test_sampler.py
- torch_points3d/datasets/segmentation/semantickitti.py
There seems to be a small typo in semantic kitti, addresses #543
> Fixing Semantic Kitti

- torch_points3d/applications/pretrained_api.py
- torch_points3d/models/registration/ms_svconv3d.py
Simple function to quickly and directly load a model from a local file.
> pretrained models from file

- README.md
Thank you for your hard work!!
I fixed a small error in the description.
> Fix wrong keyword

- docs/src/tutorials.rst
After reading your tutorial I found some typos. Hope it helps.
> some typos and redondant formulation corrected

- conf/data/segmentation/shapenet-fixed.yaml
#610 Fixed this issue by updating the shapenet-fixed.yaml file
> fixed shapenet-fixed bug

- conf/eval.yaml
- conf/visualization/eval.yaml
- eval.py
> Made a custom eval.yaml file to remove coupling between the training and evaluation visualization. 
> Update the eval.py to be match the train.py
> Updates to evaluation 

- conf/training/sparse_fragment_reg.yaml
- conf/training/sparse_fragment_reg_finetune.yaml
- poetry.lock
- pyproject.toml
- requirements.txt
- torch_points3d/models/registration/ms_svconv3d.py
- torch_points3d/models/segmentation/ms_svconv3d.py
because of Omegaconf, some models could not load on this colab [notebook](https://colab.research.google.com/github/humanpose1/MS-SVConv/blob/main/notebook/demo_MSSVConv.ipynb).
So, I correct it.
> Bug ms svconv 

- .devcontainer/setup.sh
To solve issue #627.
1. Install extension 'Remote-Container'.
2. Open command palette (`Shift+Ctrl+P`), and run `Remote-Container: Rebuild and Reopen in Container`.
3. Finish that building image is successful, VSCode opens folder into the container.
> Confirm devcontainer

- torch_points3d/metrics/model_checkpoint.py
Previously, when resuming a training run, the optimizer learning rate would reset to the original learning rate rather than the current learning rate. I suspect this is due to the order we load the states: First we initialize the optimizer then set its state to the correct lr, then we initialize the scheduler and set its state (which resets the optimizer to the scheduler's initial value). To fix, we should wait to load the optimizer's state until after we initialize the schedulers.
> Fix LR Checkpoint Resuming

- torch_points3d/trainer.py
bb97aa75d13d9ffa5f3a8511479eb713f6feff57 has moved tensorbord and wandb config under training config, thus trainer has to be updated.
> Tensorbord and wandb config has moved into training config.

- torch_points3d/modules/MinkowskiEngine/api_modules.py
- torch_points3d/modules/MinkowskiEngine/modules.py
- torch_points3d/modules/MinkowskiEngine/res16unet.py
- torch_points3d/modules/PPNet/blocks.py
- torch_points3d/modules/SparseConv3d/modules.py
The changes fixes the issue #741
> fix for issue #741
