conf/models/segmentation.yaml, models/KPConv/modules.py, models/RSConv/modules.py, models/core_modules.py, models/model_building_utils/model_definition_resolver.py, models/utils.py, test/test_config/test_resolver_in.yaml, test/test_config/test_resolver_out.yaml, test/test_models.py, test/test_resolver.py, train.py
Solves #46 
This lets users put things like `inDim: FEAT` or `nn:[FEAT*2, 16 + 16]` in the model definition. Previously these expressions had to be evaluated per argument within the convolutions. Now it is done for the entire model config before calling `find_model_using_name`
=> Add expressions and constants to model definition (globally)

find_env.py
This PR adds a file find_env.py to collect all information related to the libraries to run the project.
```My computer
(superpoint-graph-job-py3.6) ➜  ~ python find_env.py 
Collecting environment information...
PyTorch version: 1.1.0
Is debug build: No
CUDA used to build PyTorch: 9.0.176
OS: Ubuntu 18.04.2 LTS
GCC version: (Ubuntu 8.3.0-6ubuntu1~18.04.1) 8.3.0
CMake version: version 3.10.2
Python version: 3.6
Is CUDA available: Yes
CUDA runtime version: 9.1.85
GPU models and configuration: GPU 0: GeForce RTX 2060
Nvidia driver version: 418.67
cuDNN version: Could not collect
Versions of relevant libraries:
[pip3] numpy==1.18.0
[pip3] numpy-indexed==0.3.5
[pip3] torch==1.1.0
[pip3] torch-cluster==1.4.5
[pip3] torch-geometric==1.3.2
[pip3] torch-sparse==0.4.3
[pip3] torchfile==0.1.0
[pip3] …
```
=> 'Add find_env to simplify issues tracking for later use'

conf/config.yaml, datasets/shapenet_dataset.py, models/KPConv/kernels.py, models/KPConv/nn.py, models/base_model.py, models/core_modules.py, test/test_modules.py
Modules can now indicate they have internal losses by inheriting from `BaseInternalLossModule`, and implementing the abstract method `get_internal_losses`. I think this is more intuitive for users than having an instance variable which is searched for recursively. 
The method used by `BaseModel` for collecting internal losses is still similar, except now it checks if child models inherit from `BaseInternalLossModule`. I have also added a method `get_named_internal_losses` to `BaseModel`, which returns a dict of all the internal losses in the model, which will allow users to choose the weightings between different losses when calculating the overall loss.
=> ABC for modules with internal losses

models/PointNet/modules.py, models/PointNet/nn.py, models/core_transforms.py
Add a regularization loss to the linear transform STN used by pointnet to make the transform close to an orthogonal matrix. Pointnet does this so that the transform does not delete information.
=> Pointnet regularization loss

eval.py, find_neighbour_dist.py, forward_scripts/forward.py, src/datasets/base_dataset.py, src/datasets/segmentation/forward/shapenet.py, test/test_basedataset.py, test/test_shapenetforward.py, train.py
This PR forces all datasets to have a `name` property. A sub dataset can now we grabbed by name. The aim is to use that to track the provenance or a data object that was produced by one of the data loaders for example. It also clarifies some of the existing features around dataset names.
=> Give a name to all datasets

torch_points3d/core/base_conv/dense.py, torch_points3d/core/common_modules/dense_modules.py, torch_points3d/modules/RSConv/dense.py, torch_points3d/modules/pointnet2/dense.py
We lost 3% on s3dis with PN2 just because of changing from ReLU to LeakyReLU(0.1)... Putting the default to 0.01 brings the results back to previous scores, what do you think?
=> Tune default leakyReLU

README.md
Documented the crash that can happen when compiling with different GPUs, + a fix and a link to a list of architecture.
This is not an issue specific to this repo in particular, but torch-points-kernels does fail when using Turing -> Volta, and it is not well documented elsewhere.
=> added fix for kernel image fail

notebooks/dashboard.ipynb, torch_points3d/models/segmentation/pointnet.py, torch_points3d/models/segmentation/pointnet2.py, torch_points3d/models/segmentation/rsconv.py, torch_points3d/visualization/visualizer.py
Enabled visualizations to be used on segmentation of pointnet, pointnet2 and rsconv. Also, added a fix to the dashbord notebook dealing with changing the model path.
=> Enabled visualization on pointnet, pointnet2, rsconv

torch_points3d/datasets/segmentation/shapenet.py
The Shapenet dataset breaks on Windows due to faulty file path parsing, the offending code was carried from Pytorch Geometric but fixed upstream, see rusty1s/pytorch_geometric#946 and resulting rusty1s/pytorch_geometric@8bc1ba11
=> Fix filepath parsing on Windows

CHANGELOG.md, README.md, torch_points3d/datasets/base_dataset.py, torch_points3d/datasets/segmentation/shapenet.py, torch_points3d/trainer.py
Multiprocessing cannot use lambdas on Windows due to limitations with pickle. Additionally wandb currently does not run correctly on Windows wandb/client#862 therefore we recommend disabling it in the troubleshooting section of the readme
=> Windows Support

test/test_registration_metrics.py, torch_points3d/metrics/registration_metrics.py, torch_points3d/metrics/registration_tracker.py
After the kind review of @simonefontana see [here](https://github.com/nicolas-chaulet/torch-points3d/pull/420/files#diff-53d25a103d926241da472e184972f24e) for more details, I corrected the metric. It is explained at the section 3.3 of [this article](https://arxiv.org/pdf/2003.12841.pdf).
=> correct registration metrics

torch_points3d/core/common_modules/base_modules.py
Changes _forward_sparse() s.t. [N,1] tensors are output as [N,1] tensors instead of [N] #428
=> Change _forward_sparse

.devcontainer/Dockerfile, conf/data/segmentation/scannet-sparse.yaml, docker/Dockerfile, docker/Dockerfile.train, test/test_basedataset.py, torch_points3d/core/data_transform/features.py, torch_points3d/core/data_transform/grid_transform.py, torch_points3d/datasets/base_dataset.py, torch_points3d/datasets/panoptic/s3dis.py, torch_points3d/datasets/segmentation/s3dis.py, torch_points3d/datasets/segmentation/scannet.py, torch_points3d/metrics/confusion_matrix.py, torch_points3d/models/object_detection/votenet.py, torch_points3d/models/object_detection/votenet2.py, torch_points3d/modules/VoteNet/loss_helper.py, torch_points3d/trainer.py, torch_points3d/utils/geometry.py
Various small things:
- Support for class weights in the losses of votenet
- Refactor the class weight computation code + tests
- Fix tiny bug in trainer
=> Various fix and new stuff

CHANGELOG.md, forward_scripts/forward.py, test/test_model_checkpoint.py, torch_points3d/applications/pretrained_api.py, torch_points3d/metrics/model_checkpoint.py, torch_points3d/metrics/segmentation_tracker.py, torch_points3d/trainer.py
This change is required to make sure that a model can be recreated form the checkpoint only. Properties were stored in the dataset but never saved to the checkpoint. They are different from dataset configs in the sense that they capture the properties that model needs from the dataset to be created. Dataset configs are the configs that the dataset need. So I kept them separated.
=> Saving dataset properties to the checkpoint

CHANGELOG.md, README.md, conf/data/registration/testkaist.yaml, conf/data/registration/testtum.yaml, docs/src/advanced.rst, torch_points3d/datasets/registration/testkaist.py, torch_points3d/datasets/registration/testtum.py
Add Kaist and TUM datasets, as defined in https://arxiv.org/abs/2003.12841, similarly to what we have done for the ETH and Planetary datasets.
=> Pcr benchmark

torch_points3d/datasets/panoptic/utils.py
I got this warning when training panoptic segmentation on S3DIS:
`points3d/torch_points3d/datasets/panoptic/utils.py:33: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor)`
So I modified that line.
=> get rid of warning

conf/data/segmentation/shapenet_sparse.yaml, torch_points3d/models/segmentation/pvcnn.py, torch_points3d/models/segmentation/sparseconv3d.py
This PR fixes the issues described in issue #517. It enables one to run SpraseConv3D based models as follows:
```
python train.py task=segmentation model_type=sparseconv3d model_name=ResUNet32 dataset=shapenet_sparse
python train.py task=segmentation model_type=pvcnn model_name=PVCNN dataset=shapenet_sparse
```
=> Fix ShapeNet segmentation with SparseConv3D models

torch_points3d/datasets/base_dataset.py
Fix bugs of frequently occurred `Exception ignored in: function _MultiProcessingDataLoaderIter.__del__`. 
#443 
#452
=> Refine the usage of data loader with num_workers>0

CHANGELOG.md, README.md, conf/models/segmentation/sparseconv3d.yaml, conf/training/minkowski_scannet.yaml, docker/install_python.sh, torch_points3d/applications/sparseconv3d.py, torch_points3d/models/base_model.py, torch_points3d/models/segmentation/sparseconv3d.py, torch_points3d/modules/SparseConv3d/nn/__init__.py, torch_points3d/trainer.py
I added support for mixed-precision training in torchsparse (https://github.com/mit-han-lab/torchsparse/pull/69) with the following results:
> The performance of the mixed-precision training is almost the same as that of the full-precision training: 76.43 v.s. 76.78.
> The speedup is fairly limited: the total training time is reduced from 7.3 hours to 6.4 hours (around 10% reduction).
> The memory reduction is very significant: the memory usage is reduced from 48.8G to 28.8G (40% reduction).
With these commits, I added a `training.enable_mixed` flag which enables the usage of mixed precision on supported models, as well as a `_supports_mixed` variable to the models which support mixed precision (sp3d with torchsparse backend). 
To actually activate mixed precision, I wrapped the training …
=> SparseConv3D Mixed Precision Training Support

scripts/sanity_check/scannet_check.py
check if the raw dataset is downloaded correctly, if not output the scene name and automatically download them, here is an example output:
```sh
error scene: scene0100_02 | agg: False, gt: False, seg: False, ply: False
error scene: scene0603_00 | agg: False, gt: True, seg: False, ply: True
error scene: scene0024_02 | agg: False, gt: True, seg: False, ply: False
```
|scene|folder|
|----|----|
| scene0100_02 |![image](https://user-images.githubusercontent.com/2719771/123022738-d303ca80-d408-11eb-9ad6-ee90a5902a8c.png)|
|scene0603_00|![image](https://user-images.githubusercontent.com/2719771/123022918-1a8a5680-d409-11eb-803d-7e28eb4aac54.png)|
|scene0024_02|![image](https://user-images.githubusercontent.com/2719771/123022970-2c6bf980-d409-11eb-9133-19052512d86c.png)|
=> add sanity check for scannet and redownload the missing files

torch_points3d/metrics/segmentation_tracker.py
The dictionary provides the Intersection over Union (IoU) for each class, not the mIoU (mean IoU)
=> typo miou instead of iou

torch_points3d/modules/RSConv/dense.py
Fixes #735 
I digged a bit deeper into it and realized that this check/warning is most likely obsolete, and probably only there because of copy-pasting `RSConvSharedMSGDown`. Here, the `down_conv_nn` argument (or the first sublist in the case of `first_layer`) is immediately unpacked into three values. Therefore, this list must always have a length of three, independent from the radii given.
Because of this I simply removed the check. It should become clear pretty quickly if the length is invalid, since then an exception would tell something like `too many values too unpack, expected 3...`.
=> Remove obsolete check in RSConvOriginalMSGDown constructor

requirements.txt
sklearn is an obsolete dependency and breaks the `pip install`. 
Correct name of the package is `scikit-learn` and is likewise present in requirements.
=> Clean requirements 🧹
